### PR TITLE
fix implicit fallthrough

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure:

```
/home/kali/rtl8822bu/core/rtw_mlme_ext.c:1829:3: error: 'fallthrough' undeclared (first use in this function)
 1829 |   fallthrough;
      |   ^~~~~~~~~~~
```

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by ffontaine** [comment]
It should be noted that this PR is fixing a build failure with gcc 10.2.0 and should probably be mixed with #20 which fix build failure with older gcc.

**Comment by skitterrusty** [comment]
Causes build to fail on Raspberry Pi OS 'Buster'

**Comment by ffontaine** [comment]
What is the gcc version on RPi OS Buster?

**Comment by skitterrusty** [comment]
> What is the gcc version on RPi OS Buster?

GCC 8.3. 
Managed to successfully build from [1a05698].

**Comment by ffontaine** [comment]
OK, I'll try to reproduce and fix it.
`[[fallthrough]]` is a standard C++17 statement: https://en.cppreference.com/w/cpp/language/attributes/fallthrough that should be supported since gcc 7: https://gcc.gnu.org/projects/cxx-status.html. 
So at least, we should protect this call with an adequate `#ifdef`.

Perhaps, the build failure could be fixed by adding `-std=c++17`?

**Comment by ffontaine** [comment]
Can you try #22?

**Pull request merged**
