### PR TITLE
Added Edimax EW-7822UTC to the code

### PR DESCRIPTION
**Pull request by rk9qn3j**

### CODE REVIEW

**Comment by EntropicEffect** [comment]
The driver on the Edimax website for the EW-7822UTC seems to be a different version to the version hosted on this repo. I'll be happy to accept the pull request if you can confirm that it is indeed working on your device.

Unfortunately, I do not have that device so cannot test.

**Comment by rk9qn3j** [comment]
I have the device myself and I can confirm it's working. Good speed and stability. The only thing that don't seem to work is the status LED on the device.

**Comment by EntropicEffect** [comment]
Great. Thank you for the pull request.

**Comment by qtlin** [comment]
Just updated to kernel-5.10.17-200.fc33.x86_64 and inserted EW-7822UTC messes it up very badly. No meaningful information in journalctl output. Reverted to previews kernel for now.

**Pull request merged**
